In [1]:
print("Hello World")

Hello World


In [3]:
def f(x):
    return x*x          #Function for printing square of the given number.

In [5]:
f(4)



16

In [7]:
def mysum(a,b):
    return a+b
    

In [9]:
mysum(1,2)

3

In [11]:
def sqr(arr):
    result = []
    for x in arr:
        result.append(x*x)
    return result

In [13]:
t = range(100)

In [19]:
len(t)

100

In [33]:
#NUMPY ARRRAY !!!
import numpy as np
import matplotlib.pyplot as plt
import math
a = np.array([1, 2, 3, 4])
b = np.array([2,3,4,5])

In [35]:
print(a[0], a[-1])

1 4


In [37]:
a+b

array([3, 5, 7, 9])

In [39]:
a*b

array([ 2,  6, 12, 20])

In [41]:
a = np.array([[0,1,2,3],
              [10,11,12,13]]) 

In [43]:
a.shape


(2, 4)

In [45]:
a[1,3]

13

In [51]:
a = np.array([1,2,3], dtype=float)
np.ones_like(a)

array([1., 1., 1.])

In [55]:
np.ones( (2,3) )

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])